# Generated by Django 6.0.2 on 2026-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saxeli', models.CharField(max_length=100)),
                ('gvari', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('asaki', models.PositiveIntegerField()),
                ('qalaqi', models.CharField(default='თბილისი', max_length=100)),
                ('statusi', models.CharField(choices=[('aktive', 'აქტიური'), ('araaktive', 'არააქტიური'), ('blocked', 'დაბლოკილი')], default='aktive', max_length=20)),
                ('sheqmnilia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'მომხმარებელი',
                'verbose_name_plural': 'მომხმარებლები',
                'ordering': ['-sheqmnilia'],
            },
        ),
    ]
